# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('literati_geonames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geoevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('asciiname', models.CharField(help_text='Name in plain ASCII characters.', max_length=200, verbose_name='ASCII name')),
                ('date_recorded', models.DateTimeField()),
                ('magnitude', models.FloatField(default=0)),
                ('lat', models.DecimalField(decimal_places=6, help_text='latitude in decimal degrees.', max_digits=8, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=6, help_text='longitude in decimal degrees.', max_digits=9, verbose_name='longitude')),
                ('uid', models.CharField(blank=True, help_text='Unique identifier for a transaction made through an external service.', max_length=100, null=True, verbose_name='external UID')),
                ('last_modified', models.DateField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literati_geonames.AdminDivision', verbose_name='administrative division')),
            ],
            options={
                'permissions': (('autocomplete_geoevent', 'Can autocomplete geoevent'),),
                'verbose_name_plural': 'geo events',
                'verbose_name': 'geo event',
            },
        ),
        migrations.CreateModel(
            name='GeoeventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=30000)),
                ('is_active', models.BooleanField(default=True)),
                ('codename', models.CharField(help_text='Classification codename of geo event category. ', max_length=20, null=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'permissions': (('autocomplete_geoeventcategory', 'Can autocomplete geoevent category'),),
                'verbose_name_plural': 'event categories',
                'verbose_name': 'event category',
            },
        ),
        migrations.CreateModel(
            name='GeoeventSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=30000)),
                ('is_active', models.BooleanField(default=True)),
                ('details_url', models.URLField(blank=True, null=True, verbose_name='details url')),
            ],
            options={
                'permissions': (('autocomplete_geoeventsource', 'Can autocomplete geoevent source'),),
                'verbose_name_plural': 'event sources',
                'verbose_name': 'event source',
            },
        ),
        migrations.AddField(
            model_name='geoevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevents.GeoeventCategory'),
        ),
        migrations.AddField(
            model_name='geoevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoevents.Geoevent'),
        ),
        migrations.AddField(
            model_name='geoevent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoevents.GeoeventSource'),
        ),
    ]
