# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoeventsource',
            name='codename',
            field=models.CharField(help_text='Classification codename of geo event source. ', max_length=20, null=True),
        ),
    ]
