# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-16 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoevents', '0002_geoeventsource_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoevent',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='literati_geonames.AdminDivision', verbose_name='administrative division'),
        ),
    ]
